// This file was autogenerated at deployment time picking the list of blacklisted modules defined in "blacklisted-modules.js" for network staging


export const BLACKLISTED_MODULES: string[] = ["0xf575097e4028a807ffb95e4969d888e98ebfcde0", "0xbcdb6f42c754bf6ee395fc4809662987944076dc"]
