const ARAGON_COURT_ERRORS = {
  SUBSCRIPTION_NOT_PAID: 'AC_SUBSCRIPTION_NOT_PAID',
  SENDER_NOT_ARBITRABLE: 'AC_SENDER_NOT_ARBITRABLE'
}

const DISPUTE_MANAGER_ERRORS = {
  VOTER_WEIGHT_ZERO: 'DM_VOTER_WEIGHT_ZERO',
  SENDER_NOT_VOTING: 'DM_SENDER_NOT_VOTING',
  TERM_OUTDATED: 'DM_TERM_OUTDATED',
  SENDER_NOT_DISPUTE_SUBJECT: 'DM_SENDER_NOT_DISPUTE_SUBJECT',
  DISPUTE_DOES_NOT_EXIST: 'DM_DISPUTE_DOES_NOT_EXIST',
  CANNOT_CLOSE_EVIDENCE_PERIOD: 'DM_CANNOT_CLOSE_EVIDENCE_PERIOD',
  EVIDENCE_PERIOD_IS_CLOSED: 'DM_EVIDENCE_PERIOD_IS_CLOSED',
  INVALID_DISPUTE_STATE: 'DM_INVALID_DISPUTE_STATE',
  INVALID_RULING_OPTIONS: 'DM_INVALID_RULING_OPTIONS',
  DEPOSIT_FAILED: 'DM_DEPOSIT_FAILED',
  BAD_MAX_DRAFT_BATCH_SIZE: 'DM_BAD_MAX_DRAFT_BATCH_SIZE',
  ROUND_IS_FINAL: 'DM_ROUND_IS_FINAL',
  ROUND_DOES_NOT_EXIST: 'DM_ROUND_DOES_NOT_EXIST',
  INVALID_ADJUDICATION_STATE: 'DM_INVALID_ADJUDICATION_STATE',
  ROUND_ALREADY_DRAFTED: 'DM_ROUND_ALREADY_DRAFTED',
  ERROR_DRAFT_TERM_NOT_REACHED: 'DM_DRAFT_TERM_NOT_REACHED',
  ROUND_NOT_APPEALED: 'DM_ROUND_NOT_APPEALED',
  INVALID_APPEAL_RULING: 'DM_INVALID_APPEAL_RULING',
  PREV_ROUND_NOT_SETTLED: 'DM_PREVIOUS_ROUND_NOT_SETTLED',
  ROUND_ALREADY_SETTLED: 'DM_ROUND_ALREADY_SETTLED',
  ROUND_PENALTIES_NOT_SETTLED: 'DM_ROUND_PENALTIES_NOT_SETTLED',
  JUROR_ALREADY_REWARDED: 'DM_JUROR_ALREADY_REWARDED',
  WONT_REWARD_NON_VOTER_JUROR: 'DM_WONT_REWARD_NON_VOTER_JUROR',
  WONT_REWARD_INCOHERENT_JUROR: 'DM_WONT_REWARD_INCOHERENT_JUROR',
  APPEAL_ALREADY_SETTLED: 'DM_APPEAL_ALREADY_SETTLED'
}

const VOTING_ERRORS = {
  VOTE_ALREADY_EXISTS: 'CRV_VOTE_ALREADY_EXISTS',
  VOTE_DOES_NOT_EXIST: 'CRV_VOTE_DOES_NOT_EXIST',
  VOTE_ALREADY_COMMITTED: 'CRV_VOTE_ALREADY_COMMITTED',
  VOTE_ALREADY_REVEALED: 'CRV_VOTE_ALREADY_REVEALED',
  INVALID_OUTCOME: 'CRV_INVALID_OUTCOME',
  INVALID_OUTCOMES_AMOUNT: 'CRV_INVALID_OUTCOMES_AMOUNT',
  INVALID_COMMITMENT_SALT: 'CRV_INVALID_COMMITMENT_SALT',
  OWNER_MOCK_COMMIT_CHECK_REVERTED: 'CRV_OWNER_MOCK_COMMIT_CHECK_REVERTED'
}

const REGISTRY_ERRORS = {
  NOT_CONTRACT: 'JR_NOT_CONTRACT',
  INVALID_ZERO_AMOUNT: 'JR_INVALID_ZERO_AMOUNT',
  INVALID_ACTIVATION_AMOUNT: 'JR_INVALID_ACTIVATION_AMOUNT',
  INVALID_DEACTIVATION_AMOUNT: 'JR_INVALID_DEACTIVATION_AMOUNT',
  INVALID_LOCKED_AMOUNTS_LENGTH: 'JR_INVALID_LOCKED_AMOUNTS_LEN',
  INVALID_REWARDED_JURORS_LENGTH: 'JR_INVALID_REWARDED_JURORS_LEN',
  ACTIVE_BALANCE_BELOW_MIN: 'JR_ACTIVE_BALANCE_BELOW_MIN',
  NOT_ENOUGH_AVAILABLE_BALANCE: 'JR_NOT_ENOUGH_AVAILABLE_BALANCE',
  CANNOT_REDUCE_DEACTIVATION_REQUEST: 'JR_CANT_REDUCE_DEACTIVATION_REQ',
  TOKEN_TRANSFER_FAILED: 'JR_TOKEN_TRANSFER_FAILED',
  TOKEN_APPROVE_NOT_ALLOWED: 'JR_TOKEN_APPROVE_NOT_ALLOWED',
  BAD_TOTAL_ACTIVE_BALANCE_LIMIT: 'JR_BAD_TOTAL_ACTIVE_BAL_LIMIT',
  TOTAL_ACTIVE_BALANCE_EXCEEDED: 'JR_TOTAL_ACTIVE_BALANCE_EXCEEDED',
  WITHDRAWALS_LOCK: 'JR_WITHDRAWALS_LOCK'
}

const TREASURY_ERRORS = {
  DEPOSIT_AMOUNT_ZERO: 'TREASURY_DEPOSIT_AMOUNT_ZERO',
  WITHDRAW_FAILED: 'TREASURY_WITHDRAW_FAILED',
  WITHDRAW_AMOUNT_ZERO: 'TREASURY_WITHDRAW_AMOUNT_ZERO',
  WITHDRAW_INVALID_AMOUNT: 'TREASURY_WITHDRAW_INVALID_AMOUNT',
  WITHDRAWALS_DISALLOWED: 'TREASURY_WITHDRAWALS_DISALLOWED'
}

const SUBSCRIPTIONS_ERRORS = {
  SENDER_NOT_SUBSCRIBED: 'CS_SENDER_NOT_SUBSCRIBED',
  GOVERNOR_SHARE_FEES_ZERO: 'CS_GOVERNOR_SHARE_FEES_ZERO',
  TOKEN_TRANSFER_FAILED: 'CS_TOKEN_TRANSFER_FAILED',
  PERIOD_DURATION_ZERO: 'CS_PERIOD_DURATION_ZERO',
  FEE_AMOUNT_ZERO: 'CS_FEE_AMOUNT_ZERO',
  FEE_TOKEN_NOT_CONTRACT: 'CS_FEE_TOKEN_NOT_CONTRACT',
  PREPAYMENT_PERIODS_ZERO: 'CS_PREPAYMENT_PERIODS_ZERO',
  OVERRATED_GOVERNOR_SHARE_PCT: 'CS_OVERRATED_GOVERNOR_SHARE_PCT',
  RESUME_PRE_PAID_PERIODS_TOO_BIG: 'CS_RESUME_PRE_PAID_PERIODS_BIG',
  NON_PAST_PERIOD: 'CS_NON_PAST_PERIOD',
  JUROR_FEES_ALREADY_CLAIMED: 'CS_JUROR_FEES_ALREADY_CLAIMED',
  JUROR_NOTHING_TO_CLAIM: 'CS_JUROR_NOTHING_TO_CLAIM',
  PAYING_ZERO_PERIODS: 'CS_PAYING_ZERO_PERIODS',
  PAYING_TOO_MANY_PERIODS: 'CS_PAYING_TOO_MANY_PERIODS',
  LOW_RESUME_PERIODS_PAYMENT: 'CS_LOW_RESUME_PERIODS_PAYMENT',
  DONATION_AMOUNT_ZERO: 'CS_DONATION_AMOUNT_ZERO',
  COURT_HAS_NOT_STARTED: 'CS_COURT_HAS_NOT_STARTED',
  SUBSCRIPTION_PAUSED: 'CS_SUBSCRIPTION_PAUSED',
  SUBSCRIPTION_NOT_PAUSED: 'CS_SUBSCRIPTION_NOT_PAUSED'
}

const ARAGON_APP_FEES_CASHIER_ERRORS = {
  ERROR_APP_NOT_SET: 'AAFC_APP_NOT_SET',
  ERROR_WRONG_TOKEN: 'AAFC_WRONG_TOKEN',
  ERROR_COURT_HAS_NOT_STARTED: 'AAFC_COURT_HAS_NOT_STARTED',
  ERROR_WRONG_TOKENS_LENGTH: 'AAFC_WRONG_TOKENS_LENGTH',
  ERROR_WRONG_AMOUNTS_LENGTH: 'AAFC_WRONG_AMOUNTS_LENGTH'
}

const CONTROLLER_ERRORS = {
  SENDER_NOT_GOVERNOR: 'CTR_SENDER_NOT_GOVERNOR',
  INVALID_GOVERNOR_ADDRESS: 'CTR_INVALID_GOVERNOR_ADDRESS',
  IMPLEMENTATION_NOT_CONTRACT: 'CTR_IMPLEMENTATION_NOT_CONTRACT',
  INVALID_IMPLS_INPUT_LENGTH: 'CTR_INVALID_IMPLS_INPUT_LENGTH'
}

const CONTROLLED_ERRORS = {
  CONTROLLER_NOT_CONTRACT: 'CTD_CONTROLLER_NOT_CONTRACT',
  SENDER_NOT_CONTROLLER: 'CTD_SENDER_NOT_CONTROLLER',
  SENDER_NOT_DISPUTES_MODULE: 'CTD_SENDER_NOT_DISPUTES_MODULE',
  SENDER_NOT_CONFIG_GOVERNOR: 'CTD_SENDER_NOT_CONFIG_GOVERNOR'
}

const CONFIG_ERRORS = {
  TOO_OLD_TERM: 'CONF_TOO_OLD_TERM',
  INVALID_PENALTY_PCT: 'CONF_INVALID_PENALTY_PCT',
  INVALID_FINAL_ROUND_REDUCTION_PCT: 'CONF_INVALID_FINAL_ROUND_RED_PCT',
  INVALID_MAX_APPEAL_ROUNDS: 'CONF_INVALID_MAX_APPEAL_ROUNDS',
  LARGE_ROUND_PHASE_DURATION: 'CONF_LARGE_ROUND_PHASE_DURATION',
  BAD_INITIAL_JURORS_NUMBER: 'CONF_BAD_INITIAL_JURORS_NUMBER',
  BAD_APPEAL_STEP_FACTOR: 'CONF_BAD_APPEAL_STEP_FACTOR',
  ZERO_COLLATERAL_FACTOR: 'CONF_ZERO_COLLATERAL_FACTOR',
  ZERO_MIN_ACTIVE_BALANCE: 'CONF_ZERO_MIN_ACTIVE_BALANCE'
}

const CLOCK_ERRORS = {
  TERM_DOES_NOT_EXIST: 'CLK_TERM_DOES_NOT_EXIST',
  TERM_DURATION_TOO_LONG: 'CLK_TERM_DURATION_TOO_LONG',
  TERM_RANDOMNESS_NOT_YET: 'CLK_TERM_RANDOMNESS_NOT_YET',
  TERM_RANDOMNESS_UNAVAILABLE: 'CLK_TERM_RANDOMNESS_UNAVAILABLE',
  BAD_FIRST_TERM_START_TIME: 'CLK_BAD_FIRST_TERM_START_TIME',
  TOO_MANY_TRANSITIONS: 'CLK_TOO_MANY_TRANSITIONS',
  INVALID_TRANSITION_TERMS: 'CLK_INVALID_TRANSITION_TERMS',
  CANNOT_DELAY_STARTED_COURT: 'CLK_CANNOT_DELAY_STARTED_COURT',
  CANNOT_DELAY_PAST_START_TIME: 'CLK_CANNOT_DELAY_PAST_START_TIME'
}

const TREE_ERRORS = {
  UPDATE_OVERFLOW: 'SUM_TREE_UPDATE_OVERFLOW',
  KEY_DOES_NOT_EXIST: 'SUM_TREE_KEY_DOES_NOT_EXIST',
  SEARCH_OUT_OF_BOUNDS: 'SUM_TREE_SEARCH_OUT_OF_BOUNDS',
  MISSING_SEARCH_VALUES: 'SUM_TREE_MISSING_SEARCH_VALUES',
  INVALID_INTERVAL_SEARCH: 'TREE_INVALID_INTERVAL_SEARCH',
  SORTITION_LENGTHS_MISMATCH: 'TREE_SORTITION_LENGTHS_MISMATCH'
}

const CHECKPOINT_ERRORS = {
  CHECKPOINT_VALUE_TOO_BIG: 'CHECKPOINT_VALUE_TOO_BIG',
  CHECKPOINT_CANNOT_ADD_PAST_VALUE: 'CHECKPOINT_CANNOT_ADD_PAST_VALUE'
}

const MATH_ERRORS = {
  ADD_OVERFLOW: 'MATH_ADD_OVERFLOW',
  SUB_OVERFLOW: 'MATH_SUB_OVERFLOW'
}

module.exports = {
  ARAGON_COURT_ERRORS,
  DISPUTE_MANAGER_ERRORS,
  VOTING_ERRORS,
  REGISTRY_ERRORS,
  TREASURY_ERRORS,
  SUBSCRIPTIONS_ERRORS,
  ARAGON_APP_FEES_CASHIER_ERRORS,
  CONTROLLER_ERRORS,
  CONTROLLED_ERRORS,
  CONFIG_ERRORS,
  CLOCK_ERRORS,
  TREE_ERRORS,
  CHECKPOINT_ERRORS,
  MATH_ERRORS
}
